name: dta4
channels:
- pytorch
dependencies:
- python=3.7.9
- cudatoolkit
- numpy
- psutil
- opencv
- pip
- pip:
  - atari-py 
  - pyprind
  - protobuf==3.20
  - torch
  - tensorflow==1.15
  - absl-py
  - atari-py
  - gin-config
  - gym
  - tqdm
  - blosc
  - imageio
  - dopamine-rl 
  - wandb==0.16.1
  - torchvision 
 # pip install --no-deps git+https://github.com/google/dopamine.git
 

